name: Documentation

on: [push, pull_request]

env:
  DOC_SOURCE_PATH: docs
  DOC_BUILD_PATH: docs/_build/html

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
      - name: Set up CUDA and poetry
        uses: ./.github/actions/install-with-poetry
        with:
          with-cuda: true
          poetry-options: "--with=dev"
      - name: Build docs
        run: |
          cd ${{ env.DOC_SOURCE_PATH }}
          poetry run make html
      - name: Upload built docs artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.DOC_BUILD_PATH }}
          name: doc_html
      - name: Check links
        run: |
          cd ${{ env.DOC_SOURCE_PATH }}
          poetry run make linkcheck

  # Push_dev:
  #   needs: Build
  #   # Push only on the "RELEASE_next_minor" and update the "dev" documentation
  #   if: ${{ github.repository_owner == 'hyperspy' && github.ref_name == 'RELEASE_next_minor' }}
  #   permissions:
  #     # needs write permission to push the docs to gh-pages
  #     contents: write
  #   # Use the "reusable workflow" from the hyperspy organisation
  #   uses: hyperspy/.github/.github/workflows/push_doc.yml@main
  #   with:
  #     repository: 'hyperspy/hyperspy-doc'
  #     output_path: 'dev'
  #   secrets:
  #     access_token: ${{ secrets.PAT_DOCUMENTATION }}

  # Push_tag:
  #   needs: Build
  #   # Push only on tag and update the "current" documentation
  #   if: ${{ github.repository_owner == 'hyperspy' && startsWith(github.ref, 'refs/tags/') }}
  #   permissions:
  #     # needs write permission to push the docs to gh-pages
  #     contents: write
  #   # Use the "reusable workflow" from the hyperspy organisation
  #   uses: hyperspy/.github/.github/workflows/push_doc.yml@main
  #   with:
  #     repository: 'hyperspy/hyperspy-doc'
  #     output_path: 'current'
  #   secrets:
  #     access_token: ${{ secrets.PAT_DOCUMENTATION }}