name: CI
on: push
jobs:
  format-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abatilo/actions-poetry@v3.0.0
      - run: poetry install --only=dev
      - run: poetry run isort . --check
      - run: poetry run ruff check

  pytest:
    runs-on: ubuntu-latest
    container:
      image: aaherzing/etspy:latest
    steps:
    - uses: actions/checkout@v4
    - uses: abatilo/actions-poetry@v3.0.0
    - name: Install ETSpy
      run: poetry install
    - name: Run docstring example tests
      run: poetry run pytest --doctest-modules --ignore=etspy/tests etspy/ 
    - name: Run full test suite
      if: always()
      run: poetry run pytest etspy/tests/
