name: CI
on: push

jobs:
  format-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up poetry
        uses: ./.github/actions/install-with-poetry
        with:
          with-cuda: false
          poetry-options: "--only=dev"
      - run: poetry run isort . --check
      - run: poetry run ruff check

  conda-pytest:
    name: "conda pytest: (${{ matrix.python-version }}, ${{ matrix.os }}, with-cuda: ${{ matrix.with-cuda }})"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
      - name: Install with conda
        uses: ./.github/actions/install-with-conda
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run docstring example tests
        run: pytest --doctest-modules --ignore=etspy/tests etspy/ 
      - name: Run full test suite
        if: always()
        run: pytest etspy/tests/